receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  filelog:
    include:
      - /logs/*.log
    start_at: beginning
    multiline:
      line_start_pattern: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} [+-]\d{4}\]'
    operators:
      # Parse the timestamp and log level
      - type: regex_parser
        regex: '^\[(?P<timestamp>[^\]]+)\]\s+\w+\[?\d*m?(?P<level>\w+)\w*\[?\d*m?:\s+\w*\[?\d*m?(?P<message>[^\n]+)'
        parse_from: body
      
      # Extract trace context
      - type: regex_parser
        regex: 'trace_id: "(?P<trace_id>[a-f0-9]+)"'
        parse_from: body
      - type: regex_parser
        regex: 'span_id: "(?P<span_id>[a-f0-9]+)"'
        parse_from: body
      - type: regex_parser
        regex: 'trace_flags: "(?P<trace_flags>[^"]+)"'
        parse_from: body
      
      # Extract request/response data (optional)
      - type: regex_parser
        regex: 'responseTime: (?P<response_time>\d+)'
        parse_from: body
      
      # Set up trace context
      - type: trace_parser
        trace_id:
          parse_from: attributes.trace_id
        span_id:
          parse_from: attributes.span_id
      
      # Move everything to create a structured JSON body
      - type: move
        from: body
        to: attributes.original_log
      - type: move
        from: attributes.timestamp
        to: attributes.log_timestamp  
      - type: move
        from: attributes.level
        to: attributes.log_level
      - type: move
        from: attributes.message
        to: body  # This becomes the main log message

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/tempo:
    endpoint: "${TEMPO_ENDPOINT}"
    # endpoint: "tempo:4317"
    tls:
      insecure: true
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    # endpoint: "http://loki:3100/loki/api/v1/push"

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [loki, debug]
